import type { Metadata } from 'next'
import './globals.css'
import Theme from './ui/themeProvider'
import ThemeSwitch from "@/components/ThemeSwitch"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout(
  { children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Theme attribute='class' defaultTheme='dark'>
          {children}
          <h1>Hello World</h1>
          <ThemeSwitch />
        </Theme>
      </body>
    </html>
  )
}
